/*CREATE TABLE AGENDA_ADICIONAL 
   (	ID INT,
	IMAGEN VARCHAR(400), 
	URL VARCHAR(400), 
	TIPO_ENLACE INT,
	ANCHO INT,
	ALTO INT,
	DESTACADO INT,
	ID_SECCION INT
);#*/

/**/CREATE TABLE AGENDA_ADICIONAL_I 
   (	ID_ADICIONAL INT,
	ID_IDIOMA INT,
	TITULO VARCHAR(400), 
	TEXTO VARCHAR(400) 
);#*/

/*CREATE TABLE BANCORECURSOSTIC 
   (	IMAGEN_BANCO VARCHAR(100), 
	IMAGEN_CURRICULO VARCHAR(100), 
	IMAGEN_COLECCION VARCHAR(100), 
	PIE_BANCO VARCHAR(400), 
	PIE_CURRICULO VARCHAR(400), 
	PIE_COLECCION VARCHAR(400) 
);#*/

/*CREATE TABLE BLOQUETEXTO 
   (	ID INT,
	ID_ITMT INT,
	IMAGEN VARCHAR(400), 
	URL VARCHAR(400), 
	TITULO_VISIBLE VARCHAR(400), 
	PLANTILLA VARCHAR(400), 
	ORDEN INT,
	ANCHO INT,
	ALTO INT,
	FLAG_RESIZABLE VARCHAR(400), 
	FLAG_EMERGENTE VARCHAR(400) 
);#*/

/**/CREATE TABLE BLOQUETEXTO_I 
   (	ID INT,
	ID_IDIOMA INT,
	TITULO VARCHAR(400), 
	TEXTO VARCHAR(400), 
	ALTIMAGEN VARCHAR(400) 
);#*/

/*CREATE TABLE BOLETIN 
   (	ID INT,
	FECHA DATE, 
	ENVIADO INT,
	ASUNTO VARCHAR(400) 
);#*/

/**/CREATE TABLE BOLETIN_NOTICIA 
   (	ID INT,
	ID_BOLETIN INT,
	TITULO VARCHAR(400), 
	TEXTO VARCHAR(400), 
	URL VARCHAR(400) 
);#*/

/*CREATE TABLE BT 
   (	IDORIGEN INT,
	IDDESTINO INT
);#*/

/*CREATE TABLE BUSQUEDA_PREPARADA 
   (	ID_ITMT INT,
	ID_PALABRA_CLAVE INT,
	TEXTO_LIBRE VARCHAR(400) 
);#*/

/*CREATE TABLE BUSQUEDA_PREPARADA_TIPOS 
   (	ID_ITMT INT,
	ID_TIPO INT
);#*/

/*CREATE TABLE CATEGORIAS 
   (	ID INT,
	ID_ANTERIOR INT,
	ORDEN INT,
	IMAGEN VARCHAR(400), 
	FLAG_MODO VARCHAR(400) 
);#*/

/*CREATE TABLE CATEGORIAS_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400), 
	TEXTO VARCHAR(400), 
	ALTERNATIVO VARCHAR(400), 
	PIE VARCHAR(400), 
	IDTAXON VARCHAR(400) 
);#*/

/*CREATE TABLE CLASIFICACION 
   (	ID INT,
	ID_IDIOMA INT,
	VALOR VARCHAR(400), 
	ID_RECURSO INT,
	C1 VARCHAR(400), 
	C2 VARCHAR(400), 
	TAGNO INT
);#*/

/*CREATE TABLE CLAVESBUSQUEDA 
   (	ID INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE COMPETENCIA 
   (	ID INT,
	ID_ANTERIOR INT,
	ORDEN INT,
	IMAGEN VARCHAR(400), 
	FLAG_MODO VARCHAR(400) 
);#*/

/*CREATE TABLE COMPETENCIA_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400), 
	TEXTO VARCHAR(400), 
	ALTERNATIVO VARCHAR(400), 
	PIE VARCHAR(400), 
	IDTAXON VARCHAR(400) 
);#*/

/*CREATE TABLE CONTADOR 
   (	ID INT,
	PAIS VARCHAR(400), 
	NUMERO_VISITAS INT
);#*/

/*CREATE TABLE CONTENIDO_AGENDA 
   (	ID INT,
	ID_TIPO_CONTENIDO INT,
	PLANTILLA INT,
	IMAGEN VARCHAR(400), 
	FECHA DATE, 
	DESTACADO INT,
	URL VARCHAR(400), 
	ID_SECCION INT,
	LUGAR VARCHAR(400), 
	FECHA_INICIO DATE, 
	FECHA_CADUCIDAD DATE, 
	SIGUE INT,
	FECHA_FIN_EVENTO_AGENDA DATE
);#*/

/*CREATE TABLE CONTENIDO_AGENDA_I 
   (	ID_CONTENIDO INT,
	ID_IDIOMA INT,
	TITULO VARCHAR(400), 
	CONTENIDO VARCHAR(400), 
	SUBTITULO VARCHAR(400), 
	LUGAR VARCHAR(400) 
);#*/

/*CREATE TABLE CURRICULO 
   (	ID INT,
	ID_ANTERIOR INT,
	ORDEN INT,
	IMAGEN VARCHAR(400), 
	FLAG_MODO VARCHAR(400) 
);#*/

/*CREATE TABLE CURRICULO_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400), 
	TEXTO VARCHAR(400), 
	ALTERNATIVO VARCHAR(400), 
	PIE VARCHAR(400), 
	IDTAXON VARCHAR(400) 
);#*/

/*CREATE TABLE DESCRIPTOR 
   (	ID INT,
	SN VARCHAR(400), 
	FECHA VARCHAR(400) 
);#*/

/*CREATE TABLE DESCRIPTOR_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE FAQS 
   (	ID INT,
	ID_SECCION INT,
	FECHA DATE, 
	EMAIL VARCHAR(400), 
	PENDIENTE INT,
	PUBLICADO INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE FAQS_FRONT 
   (	ID INT
);#*/

/*CREATE TABLE FAQS_FRONT_I 
   (	ID INT,
	ID_IDIOMA INT,
	PREGUNTAV VARCHAR(400), 
	NOMBREAPELLIDOSV VARCHAR(400), 
	EMAILV VARCHAR(400), 
	MENSAJEOKV VARCHAR(400), 
	MENSAJEERRV VARCHAR(400), 
	PREGUNTARV VARCHAR(400), 
	CONSULTARV VARCHAR(400), 
	VOLVERV VARCHAR(400), 
	ENVIAR VARCHAR(400), 
	SINRESULTADOSV VARCHAR(400) 
);#*/

/*CREATE TABLE FAQS_I 
   (	ID_FAQS INT,
	ID_IDIOMA INT,
	TEXTO VARCHAR(400), 
	RESPUESTA VARCHAR(400) 
);#*/

/*CREATE TABLE FECHA_CONTADOR 
   (	FECHA DATE
);#*/

/*CREATE TABLE GESTORRECURSOSBIB 
   (	ID INT,
	ID_SECCION INT
);#*/

/*CREATE TABLE IDIOMAS 
   (	ID INT,
	NOMBRE VARCHAR(400), 
	ACTIVO INT,
	ALTERNATIVO VARCHAR(400) 
);#*/

/*CREATE TABLE IDIOMAS_TRADUCIR 
   (	ID INT,
	ID_IDIOMA_ORIGEN INT,
	ID_IDIOMA_DESTINO INT,
	ID_USUARIO INT
);#*/

/*CREATE TABLE INDICES_CATALOGACION_LOM 
   (	FECHA VARCHAR(400), 
	TIPO INT,
	INDICE_ACTUAL INT
);#*/

/*CREATE TABLE INFO_CENTRO 
   (	ID INT,
	NOMBRE VARCHAR(400), 
	CALLE VARCHAR(400), 
	NUMERO VARCHAR(400), 
	CP VARCHAR(400), 
	CIUDAD VARCHAR(400), 
	EMAIL VARCHAR(400), 
	TELEFONO VARCHAR(400), 
	FAX VARCHAR(400), 
	PROVINCIA VARCHAR(400), 
	IMAGEN VARCHAR(400), 
	URL VARCHAR(400), 
	UPLOAD_DIR VARCHAR(400) 
);#*/

/*CREATE TABLE IPS_CONTADOR 
   (	IP VARCHAR(400) 
);#*/

/*CREATE TABLE ITMT 
   (	ID INT,
	ID_ANTERIOR INT,
	IMAGEN VARCHAR(400), 
	FLAG_MODO INT,
	ORDEN INT,
	VISIBLE INT,
	LINK_A_SECCION INT,
	LINK_EXTERNO VARCHAR(400), 
	FLAG_EMERGENTE INT,
	ANCHO INT,
	ALTO INT,
	URL_TEXTO VARCHAR(400), 
	FLAG_INDICE INT,
	FLAG_RESIZABLE VARCHAR(400), 
	PRIMERO VARCHAR(400) 
);#*/

/*CREATE TABLE ITMT_I 
   (	ID INT,
	ID_IDIOMA INT,
	TITULO VARCHAR(400), 
	ENTRADILLA VARCHAR(400), 
	ALTIMAGEN VARCHAR(400), 
	ENTRADILLA_LISTA_DESCARGA VARCHAR(400) 
);#*/

/*CREATE TABLE LISTA_DESCARGA 
   (	ID INT,
	ID_ITMT INT,
	URL VARCHAR(400), 
	ORDEN INT,
	FLAG_EMERGENTE VARCHAR(400), 
	FLAG_RESIZABLE VARCHAR(400), 
	ANCHO VARCHAR(400), 
	ALTO VARCHAR(400), 
	DESCARGA_DIRECTA VARCHAR(400), 
	TIPO_DESCARGA VARCHAR(400), 
	URL_TITULO VARCHAR(400) 
);#*/

/*CREATE TABLE LISTA_DESCARGA_I 
   (	ID INT,
	ID_IDIOMA INT,
	TITULO VARCHAR(400), 
	TEXTO VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_ANN 
   (	ID INT
);#*/

/*CREATE TABLE LOM_ANN_ASSOC 
   (	ID_LOM INT,
	ID_ANN INT
);#*/

/*CREATE TABLE LOM_ANN_DATE 
   (	ID INT,
	ID_DATE INT
);#*/

/*CREATE TABLE LOM_ANN_DESC 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_ANN_ENTITY 
   (	ID INT,
	ID_CENTITY INT
);#*/

/*CREATE TABLE LOM_CLASSIFICATION 
   (	ID INT
);#*/

/*CREATE TABLE LOM_CLASSIFICATION_ASSOC 
   (	ID_LOM INT,
	ID_CLASSIFICATION INT
);#*/

/*CREATE TABLE LOM_CLASSIFICATION_DESC 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_CLASSIFICATION_KEY 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_CLASSIFICATION_PURPOSE 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_CLASSIFICATION_TAXONPATH 
   (	ID INT,
	ID_TAXONPATH INT
);#*/

/*CREATE TABLE LOMD_ACCESO 
   (	ID INT
);#*/

/*CREATE TABLE LOMD_ACCESO_DESC 
   (	ID_ACCESO INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOMD_ACCESO_TYPE 
   (	ID_ACCESO INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOMD_CENTITY 
   (	ID INT,
	DATA VARCHAR(400) 
);#*/

/*CREATE TABLE LOMD_CONTRIBUTE 
   (	ID INT,
	ROLE INT,
	FECHA INT
);#*/

/*CREATE TABLE LOMD_CONTRIBUTE_CENTITY 
   (	ID_CONTRIBUTE INT,
	ID_CENTITY INT
);#*/

/*CREATE TABLE LOMD_DATE 
   (	ID INT,
	DATA DATE
);#*/

/*CREATE TABLE LOMD_DATE_DESCRIPTION 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOMD_DURATION 
   (	ID INT,
	YEARS INT,
	MONTHS INT,
	DAYS INT,
	HOURS INT,
	MINUTES INT,
	SECONDS INT
);#*/

/*CREATE TABLE LOMD_DURATION_DESCRIPTION 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOMD_IDENTIFIER 
   (	ID INT,
	CATALOG VARCHAR(400), 
	ENTRY VARCHAR(400) 
);#*/

/*CREATE TABLE LOMD_LANGS 
   (	ID INT,
	LANG VARCHAR(400), 
	NAME VARCHAR(400) 
);#*/

/*CREATE TABLE LOMD_LANGSTRING 
   (	ID INT,
	ID_LANG INT,
	STRING VARCHAR(400) 
);#*/

/*CREATE TABLE LOMD_LANGSTRINGLISTA 
   (	ID INT,
	XMLTAG VARCHAR(400) 
);#*/

/*CREATE TABLE LOMD_RESOURCE 
   (	ID INT
);#*/

/*CREATE TABLE LOMD_RESOURCE_DESC 
   (	ID_RESOURCE INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOMD_RESOURCE_ID 
   (	ID_RESOURCE INT,
	ID_IDENTIFIER INT
);#*/

/*CREATE TABLE LOMD_TAXON 
   (	ID INT,
	STRID VARCHAR(400), 
	ENTRY INT,
	TIPO_CLAS INT
);#*/

/*CREATE TABLE LOMD_TAXONPATH 
   (	ID INT,
	SOURCE INT
);#*/

/*CREATE TABLE LOMD_TAXONPATH_TAXON 
   (	ID_TAXON INT,
	ID_TAXONPATH INT,
	ORDEN INT
);#*/

/*CREATE TABLE LOMD_TECHREQ 
   (	ID INT
);#*/

/*CREATE TABLE LOMD_TECHREQ_ASSOC 
   (	ID_REQ INT,
	ID_OR INT
);#*/

/*CREATE TABLE LOMD_TECHREQ_OR 
   (	ID INT,
	TYPE INT,
	NAME INT,
	MINIMUMVERSION VARCHAR(400), 
	MAXIMUMVERSION VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_EDU 
   (	ID INT
);#*/

/*CREATE TABLE LOM_EDU_AGERANGE 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_EDU_ASSOC 
   (	ID_LOM INT,
	ID_EDU INT
);#*/

/*CREATE TABLE LOM_EDU_COGNITIVO 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_EDU_CONTEXT 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_EDU_DESCRIPTION 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_EDU_DIFFICULTY 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_EDU_INTERLEVEL 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_EDU_INTERTYPE 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_EDU_LANGUAGE 
   (	ID INT,
	ID_LANG INT
);#*/

/*CREATE TABLE LOM_EDU_LEARNTIME 
   (	ID INT,
	ID_DURATION INT
);#*/

/*CREATE TABLE LOM_EDU_RESTYPE 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_EDU_SEMDENSITY 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_EDU_USERROLE 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_GENERAL 
   (	ID INT
);#*/

/*CREATE TABLE LOM_GENERAL_AGGREGATION 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_GENERAL_COVERAGE 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_GENERAL_DESCRIPTION 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_GENERAL_ID 
   (	ID INT,
	ID_IDENTIFIER INT
);#*/

/*CREATE TABLE LOM_GENERAL_KEYWORD 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_GENERAL_LANGUAGE 
   (	ID INT,
	ID_LANG INT
);#*/

/*CREATE TABLE LOM_GENERAL_STRUCTURE 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_GENERAL_TITLE 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_ID 
   (	ID INT
);#*/

/*CREATE TABLE LOM_LIFECYCLE 
   (	ID INT
);#*/

/*CREATE TABLE LOM_LIFECYCLE_CONTRIBUTE 
   (	ID INT,
	ID_CONTRIBUTE INT,
	ORDEN INT
);#*/

/*CREATE TABLE LOM_LIFECYCLE_STATUS 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_LIFECYCLE_VERSION 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_META 
   (	ID INT
);#*/

/*CREATE TABLE LOM_META_CONTRIBUTE 
   (	ID INT,
	ID_CONTRIBUTE INT,
	ORDEN INT
);#*/

/*CREATE TABLE LOM_META_ID 
   (	ID INT,
	ID_IDENTIFIER INT
);#*/

/*CREATE TABLE LOM_META_LANG 
   (	ID INT,
	LANG VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_META_SCHEMA 
   (	ID INT,
	SCHEMA1 VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_RELATION 
   (	ID INT
);#*/

/*CREATE TABLE LOM_RELATION_ASSOC 
   (	ID_LOM INT,
	ID_RELATION INT
);#*/

/*CREATE TABLE LOM_RELATION_KIND 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_RELATION_RESOURCE 
   (	ID INT,
	ID_RESOURCE INT
);#*/

/*CREATE TABLE LOM_RIGHTS 
   (	ID INT
);#*/

/*CREATE TABLE LOM_RIGHTS_ACCESO 
   (	ID INT,
	ID_ACCESO INT
);#*/

/*CREATE TABLE LOM_RIGHTS_COPYRIGHT 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_RIGHTS_COST 
   (	ID INT,
	ID_VOC_VALOR INT
);#*/

/*CREATE TABLE LOM_RIGHTS_DESCRIPTION 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_TECH 
   (	ID INT
);#*/

/*CREATE TABLE LOM_TECH_DURATION 
   (	ID INT,
	ID_DURATION INT
);#*/

/*CREATE TABLE LOM_TECH_FORMAT 
   (	ID INT,
	FORMAT VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_TECH_INSTALL 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_TECH_LOCATION 
   (	ID INT,
	LOCATION VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_TECH_OTHER 
   (	ID INT,
	ID_LANGSTRINGLISTA INT
);#*/

/*CREATE TABLE LOM_TECH_REQUIREMENT 
   (	ID INT,
	ID_REQUIREMENT INT
);#*/

/*CREATE TABLE LOM_TECH_SIZE 
   (	ID INT,
	TAMANIO VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_TOOLTIP 
   (	TEXTREF VARCHAR(400), 
	INFO VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_VOC 
   (	ID INT,
	XML_TAG_NAME VARCHAR(400), 
	NOMBRE VARCHAR(400), 
	DESCRIPTION VARCHAR(400), 
	SOURCE VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_VOC_ASSOC 
   (	ID_VOC INT,
	ID_VALOR INT
);#*/

/*CREATE TABLE LOM_VOC_DEPENDENCIAS 
   (	ID_VOC INT,
	ID_VOC_ID INT,
	ID_VOC_DEP INT,
	ID_VOC_DEP_ID INT
);#*/

/*CREATE TABLE LOM_VOC_TEXTREF 
   (	REF VARCHAR(400), 
	ID_VOC INT
);#*/

/*CREATE TABLE LOM_VOC_VALORES 
   (	ID INT,
	ID_ORDEN INT,
	XML_VALUE VARCHAR(400) 
);#*/

/*CREATE TABLE LOM_VOC_VALORES_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400), 
	DESCRIPCION VARCHAR(400) 
);#*/

/*CREATE TABLE MENU_Y_TEXTO 
   (	ID INT,
	PLANTILLA VARCHAR(400) 
);#*/

/*CREATE TABLE MESES 
   (	ID INT,
	ORDEN INT
);#*/

/*CREATE TABLE MESES_I 
   (	ID_MES INT,
	ID_IDIOMA INT,
	TEXTO VARCHAR(400) 
);#*/

/*CREATE TABLE METAINFORMACION 
   (	ID INT,
	DESCRIPCION VARCHAR(400), 
	PALABRAS_CLAVE VARCHAR(400) 
);#*/

/*CREATE TABLE MICROTESAUROS 
   (	ID INT
);#*/

/*CREATE TABLE MICROTESAUROS_I 
   (	ID INT,
	ID_IDIOMA INT,
	DESCRIPCION VARCHAR(400) 
);#*/

/*CREATE TABLE MTCONDESC 
   (	IDMICROTESAURO INT,
	IDDESCRIPTOR INT
);#*/

/*CREATE TABLE NODESCRIPTOR 
   (	ID INT,
	IDDESCRIPTORUSE INT,
	IDDESCRIPTORUF INT
);#*/

/*CREATE TABLE NODESCRIPTOR_I 
   (	ID INT,
	ID_IDIOMA INT,
	DESCRIPCION VARCHAR(400) 
);#*/

/*CREATE TABLE NOTICIAS 
   (	ID INT,
	IMAGEN VARCHAR(400), 
	PLANTILLA VARCHAR(400), 
	DESTACADA VARCHAR(400), 
	LUGAR VARCHAR(400), 
	FECHA VARCHAR(400) 
);#*/

/*CREATE TABLE NOTICIAS_I 
   (	ID INT,
	ID_IDIOMA INT,
	TITULO VARCHAR(400), 
	TEXTO VARCHAR(400), 
	INTRODUCCION VARCHAR(400), 
	ALTIMAGEN VARCHAR(400) 
);#*/

/*CREATE TABLE NT 
   (	IDORIGEN INT,
	IDDESTINO INT
);#*/

/*CREATE TABLE PAISES 
   (	ID INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE PUBLICACIONES 
   (	ID INT,
	ID_SECCION INT,
	ID_TIPO INT,
	AUTOR VARCHAR(400), 
	EDITORIAL VARCHAR(400), 
	LUGAR_PUBLICACION VARCHAR(400), 
	ANIO INT,
	ISBN VARCHAR(400), 
	NIPO VARCHAR(400), 
	REFERENCIA VARCHAR(400), 
	URL VARCHAR(400), 
	IMAGEN VARCHAR(400), 
	PDF VARCHAR(400), 
	ORDEN INT,
	NUMERO INT
);#*/

/*CREATE TABLE PUBLICACIONES_I 
   (	ID INT,
	ID_IDIOMA INT,
	TITULO VARCHAR(400), 
	TEXTO_URL VARCHAR(400), 
	TEXTO_IMAGEN VARCHAR(400), 
	RESENIA VARCHAR(400) 
);#*/

/*CREATE TABLE PUBLICACIONES_SOP_MAT 
   (	ID_PUBLICACION INT,
	ID_SOPORTE INT
);#*/

/*CREATE TABLE PUBLICACIONES_SOPORTES 
   (	ID INT,
	ORDEN INT
);#*/

/*CREATE TABLE PUBLICACIONES_SOPORTES_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE PUBLICACIONES_TIPOS 
   (	ID INT,
	ORDEN INT
);#*/

/*CREATE TABLE PUBLICACIONES_TIPOS_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_AREA 
   (	ID INT,
	AREA VARCHAR(400), 
	PERSONA_CONTACTO VARCHAR(400), 
	EMAIL VARCHAR(400), 
	TELEFONO VARCHAR(400), 
	LENGUAS_DOCENCIA VARCHAR(400), 
	DIRIGIDAS_A VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_ARTICULOS_PERSONA 
   (	ID_PERSONA INT,
	ID_ARTICULO INT
);#*/

/*CREATE TABLE QEQ_FORMACION_AREA_INS 
   (	ID_INSTITUCION INT,
	ID_AREA INT
);#*/

/*CREATE TABLE QEQ_INSTITUCIONES 
   (	TIPO INT,
	DIRECCION VARCHAR(400), 
	OTRAS_SEDES VARCHAR(400), 
	TELEFONO VARCHAR(400), 
	FAX VARCHAR(400), 
	EMAIL VARCHAR(400), 
	WEB VARCHAR(400), 
	INFO_OCULTA VARCHAR(400), 
	ID INT,
	ID_SECCION INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_INSTITUCIONES_I 
   (	ID INT,
	ID_IDIOMA INT,
	DESCRIPCION VARCHAR(400), 
	OBSERVACIONES VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_PERS_ARTICULO 
   (	ID INT,
	ENLACE VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_PERS_ARTICULO_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_PERSONA 
   (	ID INT,
	NOMBRE VARCHAR(400), 
	APELLIDOS VARCHAR(400), 
	TELEFONO VARCHAR(400), 
	FAX VARCHAR(400), 
	EMAIL VARCHAR(400), 
	WEB VARCHAR(400), 
	ID_SECCION INT
);#*/

/*CREATE TABLE QEQ_PERSONA_I 
   (	ID INT,
	ID_IDIOMA INT,
	AREAS VARCHAR(400), 
	CARGO VARCHAR(400), 
	OBSERVACIONES VARCHAR(400), 
	INSTITUCION VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_PERS_PUBLICACION 
   (	ID INT,
	ENLACE VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_PERS_PUBLICACION_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400), 
	ADICIONAL VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_PUBLICACIONES_PERSONA 
   (	ID_PERSONA INT,
	ID_PUBLICACION INT
);#*/

/*CREATE TABLE QEQ_RECURSOS 
   (	ID INT,
	ORDEN INT
);#*/

/*CREATE TABLE QEQ_RECURSOS_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_RECURSOS_INSTITUCIONES 
   (	ID_INSTITUCION INT,
	ID_RECURSO INT
);#*/

/*CREATE TABLE QEQ_TEMAS_INSTITUCIONES 
   (	ID_TIPO_TEMAS_INS INT,
	ID_INSTITUCIONES INT
);#*/

/*CREATE TABLE QEQ_TIPO_INSTITUCION 
   (	ID INT,
	ORDEN INT
);#*/

/*CREATE TABLE QEQ_TIPO_INSTITUCION_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE QEQ_TIPO_TEMAS_INS 
   (	ID INT,
	ORDEN INT
);#*/

/*CREATE TABLE QEQ_TIPO_TEMAS_INS_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE RECURSO_BANCO_TIC 
   (	ID INT,
	LOM_ID INT,
	RUTA VARCHAR(400), 
	INDICE VARCHAR(400), 
	USUARIO_ID INT,
	FECHA VARCHAR(400), 
	FLAG_ZIP VARCHAR(400), 
	FLAG_THUMBNAIL VARCHAR(400), 
	FLAG_URL VARCHAR(400), 
	VALIDADO VARCHAR(400), 
	IP VARCHAR(400) 
);#*/

/*CREATE TABLE RECURSOS 
   (	ID INT,
	ID_TIPO_RECURSO INT,
	ID_RECURSOS_BIBLIOGRAFICOS INT,
	ID_REGISTRO_MARC INT
);#*/

/*CREATE TABLE RECURSOSBIB_FRONT 
   (	ID INT,
	FLAG_PALABRAS_CLAVE_VISIBLES VARCHAR(400) 
);#*/

/*CREATE TABLE RECURSOSBIB_FRONT_I 
   (	ID INT,
	ID_IDIOMA INT,
	TITULO VARCHAR(400), 
	OTROS_TITULO VARCHAR(400), 
	TITULO_RELACIONADO VARCHAR(400), 
	AUTOR VARCHAR(400), 
	AUTOR_ENTIDAD VARCHAR(400), 
	AUTOR_CONGRESO VARCHAR(400), 
	AUTOR_SECUNDARIO VARCHAR(400), 
	AUTOR_SECUNDARIO_ENTIDAD VARCHAR(400), 
	AUTOR_SECUNDARIO_CONGRESO VARCHAR(400), 
	RESUMEN VARCHAR(400), 
	NIVEL VARCHAR(400), 
	BIBLIOGRAFIA VARCHAR(400), 
	DESCRIPTOR_ESDM VARCHAR(400), 
	DESCRIPTOR_NO_TESAURO VARCHAR(400), 
	DESCRIPCION_FISICA VARCHAR(400), 
	NOTA_FORMATO VARCHAR(400), 
	IDIOMA_SECUNDARIO VARCHAR(400), 
	AREA_EDICION VARCHAR(400), 
	TITULO_SERIE VARCHAR(400), 
	ISBN VARCHAR(400), 
	COMUNIDAD VARCHAR(400), 
	OBRA_PUBLICADA VARCHAR(400), 
	NUMERO_SOPORTE VARCHAR(400), 
	NOTA_RESTRICCIONES VARCHAR(400), 
	NOTA_CONDICIONES VARCHAR(400), 
	DIRECCION_ELECTRONICA VARCHAR(400), 
	ASIENTO VARCHAR(400), 
	PUNTOS_FUERTES VARCHAR(400), 
	DISPONIBLE_BIBLIOTECA VARCHAR(400), 
	TIPO VARCHAR(400), 
	TEMA VARCHAR(400), 
	TEXTO_LIBRE VARCHAR(400), 
	PALABRA_CLAVE VARCHAR(400), 
	EDITORIAL VARCHAR(400), 
	LUGAR_PUBLICACION VARCHAR(400), 
	TODOS VARCHAR(400), 
	DESCRIPTOR_TESAURO VARCHAR(400), 
	LOCALIZACION VARCHAR(400) 
);#*/

/*CREATE TABLE REGISTRO_MARC 
   (	ID INT,
	NUMERO_REGISTRO INT
);#*/

/*CREATE TABLE RT 
   (	IDORIGEN INT,
	IDDESTINO INT
);#*/

/*CREATE TABLE RUTA_FICHEROS 
   (	RUTA VARCHAR(400), 
	RUTA_HD VARCHAR(400) 
);#*/

/*CREATE TABLE SECCION 
   (	ID INT,
	TIPO_SECCION INT,
	CABECERA VARCHAR(400), 
	VISIBLE INT,
	ORDEN INT,
	FLAG_INDICE INT,
	FLAG_SEGUNDA_BARRA VARCHAR(400), 
	FLAG_PRIMERA_BARRA VARCHAR(400), 
	PLANTILLA_MENU VARCHAR(400), 
	PORTADA_IMAGEN VARCHAR(400), 
	PORTADA_ALTIMAGEN VARCHAR(400), 
	PORTADA_ACTIVA VARCHAR(400), 
	PORTADA_BORDE VARCHAR(400), 
	ICONO VARCHAR(400), 
	URL_LINK VARCHAR(400), 
	FLAG_FAQ_ACTIVO INT DEFAULT 1
);#*/

/*CREATE TABLE SECCIONES_TRADUCIR 
   (	ID INT,
	ID_USUARIO INT,
	ID_SECCION INT
);#*/

/*CREATE TABLE SECCION_I 
   (	ID INT,
	ID_IDIOMA INT,
	TITULO VARCHAR(400), 
	EXPLICACION VARCHAR(400), 
	PORTADA_TEXTO VARCHAR(400) 
);#*/

/*CREATE TABLE SECCION_NOTICIAS 
   (	ID_SECCION INT,
	ID_NOTICIAS INT,
	ID INT
);#*/

/*CREATE TABLE SMTP_SERVER 
   (	HOST VARCHAR(400), 
	PUERTO INT,
	USUARIO VARCHAR(400), 
	PASSWORD VARCHAR(400), 
	SSL_AUTH VARCHAR(2), 
	REMITENTE VARCHAR(400) 
);#*/

/*CREATE TABLE SUBSCRIBIRSE_FRONT 
   (	ID INT
);#*/

/*CREATE TABLE SUBSCRIBIRSE_FRONT_I 
   (	ID INT,
	ID_IDIOMA INT,
	MSGERRALTA VARCHAR(400), 
	MSGOKALTA VARCHAR(400), 
	MSGERRBAJA VARCHAR(400), 
	MSGOKBAJA VARCHAR(400), 
	MSGQUIEROBORRAR VARCHAR(400), 
	MSGCAMPOSINCORRECTOS VARCHAR(400) 
);#*/

/*CREATE TABLE SUGERENCIA 
   (	ID INT,
	NOMBRE VARCHAR(400), 
	EMAIL VARCHAR(400), 
	SUGERENCIA VARCHAR(400), 
	LEIDO INT
);#*/

/*CREATE TABLE SUGERENCIAS_FRONT 
   (	ID INT
);#*/

/*CREATE TABLE SUGERENCIAS_FRONT_I 
   (	ID INT,
	ID_IDIOMA INT,
	MENSAJEOKV VARCHAR(400), 
	MENSAJEERRV VARCHAR(400) 
);#*/

/*CREATE TABLE SUSCRIPTORES 
   (	ID INT,
	NOMBRE VARCHAR(400), 
	INSTITUCION_RELACION VARCHAR(400), 
	EMAIL VARCHAR(400), 
	BOLETINES_ENVIADOS VARCHAR(400), 
	INSTITUCION_NOMBRE VARCHAR(400), 
	DIRECCION VARCHAR(400), 
	CP INT,
	LOCALIDAD VARCHAR(400), 
	PROVINCIA VARCHAR(400), 
	PAIS INT
);#*/

/*CREATE TABLE TAX_ACCESIBILIDAD 
   (	ID INT,
	ID_ANTERIOR INT,
	ORDEN INT,
	IMAGEN VARCHAR(400), 
	FLAG_MODO VARCHAR(400) 
);#*/

/*CREATE TABLE TAX_ACCESIBILIDAD_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400), 
	TEXTO VARCHAR(400), 
	ALTERNATIVO VARCHAR(400), 
	PIE VARCHAR(400), 
	IDTAXON VARCHAR(400) 
);#*/

/*CREATE TABLE TAXONOMIA_MAPEO 
   (	PURPOSE VARCHAR(400), 
	SOURCE VARCHAR(400), 
	TABLA VARCHAR(400) 
);#*/

/*CREATE TABLE TAXONOMIA_ULTIMOID 
   (	TABLA VARCHAR(400), 
	ID INT,
	SOURCE VARCHAR(400) 
);#*/

/*CREATE TABLE TIPO_CONTENIDO 
   (	ID INT
);#*/

/*CREATE TABLE TIPO_CONTENIDO_I 
   (	ID_TIPO_CONTENIDO INT,
	ID_IDIOMA INT,
	SINGULAR VARCHAR(400), 
	PLURAL VARCHAR(400) 
);#*/

/*CREATE TABLE TIPORECURSO 
   (	ID INT
);#*/

/*CREATE TABLE TIPORECURSO_I 
   (	ID INT,
	ID_IDIOMA INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE TRADUCTORES_VOCABULARIO 
   (	ID INT
);#*/

/*CREATE TABLE USUARIOS 
   (	ID INT,
	USUARIO VARCHAR(400), 
	PASS VARCHAR(400), 
	NIVEL_ACCESO INT,
	NOMBRE VARCHAR(400), 
	DIRECCION VARCHAR(400), 
	APELLIDOS VARCHAR(400), 
	LOCALIDAD VARCHAR(400), 
	CP VARCHAR(400), 
	PROVINCIA VARCHAR(400), 
	DNI VARCHAR(400), 
	TELEFONO VARCHAR(400), 
	MOVIL VARCHAR(400), 
	EMAIL VARCHAR(400) 
);#*/

/*CREATE TABLE VOCABULARIO 
   (	ID INT,
	NOMBRE VARCHAR(400) 
);#*/

/*CREATE TABLE VOCABULARIO_I 
   (	ID INT,
	ID_IDIOMA INT,
	CADENA VARCHAR(400) 
);#*/
